# Generated by Django 5.0.3 on 2024-03-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_app', '0002_scrapeddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedData',
        ),
    ]
